### PR TITLE
15

### LINKED ISSUE #15: tests for things that look like access

### PR DESCRIPTION
**Pull request by thedavidmeister**
fixes #15 

THIS IS WIP

### CODE REVIEW

**Comment by thedavidmeister** [comment]
ah, annoying that i setup circle on my fork but it doesn't show builds here in the PR

https://circleci.com/gh/thedavidmeister/covenant/4

**Comment by thedavidmeister** [comment]
@flyboarder should these validate? all three currently return `true` from covenant but none have the `:admin` role.

```
 ; removing the admin role should not validate
 (doseq [t [{} {:roles #{}} {:roles #{:editor}}]]
  (is
   (not (covenant.core/validate {:roles #{:admin}} t))
   (str (pr-str t) " validated as admin"))))
```

**Comment by thedavidmeister** [comment]
@flyboarder mmm, would you like me to look at extending the validation logic?

**Comment by flyboarder** [comment]
@thedavidmeister it's ok, lets move on assuming the validation works

**Comment by flyboarder** [comment]
I'm working on fixing up the logic

**Pull request merged**
